version: '3'

services:
  db_postgres:
    container_name: 'db_eventos'
    image: 'postgres:14.2-alpine'
    restart: always
    environment:
      POSTGRES_USER: hugo
      POSTGRES_PASSWORD: 78711
      POSTGRES_DB: bancoapi
    ports:
      - '5435:5432'
    volumes:
      - ./database/eventos:/var/lib/postgresql/data/

  be_eventos:
    entrypoint: /bin/sh './scripts/be-node-dev.sh'
    env_file:
      - .env
    ports:
      - '4000:4000'
    depends_on:
      - db_postgres
    links:
      - db_postgres

  be_eventos_test:
    container_name: 'be_eventos_test'
    command: sh -c "echo 'Test container ready' && tail -f /dev/null"
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - db_postgres
    links:
      - db_postgres
    env_file:
      - .env
    volumes:
      - .:/app/
      - /app/node_modules

  fe_eventos:
    container_name: 'fe_eventos'
    build:
      context: ./frontend  
      dockerfile: Dockerfile  
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app  
      - /app/node_modules
